import { Listing } from '@/types';

const demoUser = {
  id: 'demo',
  firstName: 'BizPartner',
  lastName: 'AL',
  email: 'demo@bizpartner.al',
  role: 'PUBLISHER' as const,
  isVerified: true,
  isEmailVerified: true,
  isActive: true,
  createdAt: '2026-01-01T00:00:00Z',
  updatedAt: '2026-01-01T00:00:00Z',
};

export const mockJobs: Listing[] = [
  {
    id: 'mock-job-1',
    title: 'Senior Full-Stack Developer',
    slug: 'senior-full-stack-developer',
    description: 'Join our growing tech company as a Senior Full-Stack Developer. Work with React, Node.js, and PostgreSQL on cutting-edge Albanian e-commerce platforms. Remote-friendly team, competitive salary.',
    type: 'JOB',
    status: 'ACTIVE',
    price: 3500,
    priceUnit: '/month',
    currency: 'EUR',
    city: 'Tirana',
    country: 'Albania',
    images: ['https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=800&auto=format&fit=crop'],
    tags: ['react', 'nodejs', 'typescript'],
    views: 342,
    isFeatured: true,
    isPremium: true,
    isUrgent: false,
    createdAt: '2026-05-20T10:00:00Z',
    updatedAt: '2026-05-20T10:00:00Z',
    userId: 'demo',
    categoryId: 'cat-tech',
    category: { id: 'cat-tech', name: 'Technology', slug: 'technology', icon: '💻', listingType: 'JOB' },
    user: demoUser,
    jobDetails: {
      id: 'jd-1',
      listingId: 'mock-job-1',
      jobType: 'FULL_TIME',
      experienceLevel: 'Senior',
      isRemote: true,
      salaryMin: 3000,
      salaryMax: 4000,
      salaryCurrency: 'EUR',
      salaryPeriod: 'MONTHLY',
      skills: ['React', 'Node.js', 'TypeScript', 'PostgreSQL'],
      benefits: ['Health insurance', 'Remote work', 'Annual bonus'],
      requirements: ['5+ years experience', 'Strong TypeScript skills'],
      responsibilities: ['Lead development team', 'Code reviews'],
      openPositions: 2,
      companyName: 'TechAlbania',
      companyWebsite: 'https://techalb.com',
    },
  },
  {
    id: 'mock-job-2',
    title: 'UI/UX Designer',
    slug: 'ui-ux-designer-tirana',
    description: 'We are looking for a talented UI/UX Designer to create beautiful and intuitive digital experiences. You will work closely with our product and engineering teams in Tirana.',
    type: 'JOB',
    status: 'ACTIVE',
    price: 1800,
    priceUnit: '/month',
    currency: 'EUR',
    city: 'Tirana',
    country: 'Albania',
    images: ['https://images.unsplash.com/photo-1626785774625-ddcddc3445e9?w=800&auto=format&fit=crop'],
    tags: ['figma', 'design', 'ux'],
    views: 218,
    isFeatured: false,
    isPremium: false,
    isUrgent: false,
    createdAt: '2026-05-19T09:00:00Z',
    updatedAt: '2026-05-19T09:00:00Z',
    userId: 'demo',
    categoryId: 'cat-design',
    category: { id: 'cat-design', name: 'Design', slug: 'design', icon: '🎨', listingType: 'JOB' },
    user: demoUser,
    jobDetails: {
      id: 'jd-2',
      listingId: 'mock-job-2',
      jobType: 'FULL_TIME',
      experienceLevel: 'Mid-Level',
      isRemote: false,
      salaryMin: 1500,
      salaryMax: 2200,
      salaryCurrency: 'EUR',
      salaryPeriod: 'MONTHLY',
      skills: ['Figma', 'Adobe XD', 'Prototyping'],
      benefits: ['Flexible hours', 'Modern office'],
      requirements: ['3+ years experience', 'Strong portfolio'],
      responsibilities: ['Design wireframes', 'User research'],
      openPositions: 1,
      companyName: 'DigitalAL',
    },
  },
  {
    id: 'mock-job-3',
    title: 'Digital Marketing Manager',
    slug: 'digital-marketing-manager-albania',
    description: 'Seeking an experienced Digital Marketing Manager to lead our online campaigns across social media, SEO, and paid advertising. Must have proven results in the Albanian market.',
    type: 'JOB',
    status: 'ACTIVE',
    price: 1500,
    priceUnit: '/month',
    currency: 'EUR',
    city: 'Durrës',
    country: 'Albania',
    images: ['https://images.unsplash.com/photo-1432888622747-4eb9a8f5f366?w=800&auto=format&fit=crop'],
    tags: ['marketing', 'seo', 'social-media'],
    views: 156,
    isFeatured: false,
    isPremium: false,
    isUrgent: true,
    createdAt: '2026-05-21T11:00:00Z',
    updatedAt: '2026-05-21T11:00:00Z',
    userId: 'demo',
    categoryId: 'cat-marketing',
    category: { id: 'cat-marketing', name: 'Marketing', slug: 'marketing', icon: '📣', listingType: 'JOB' },
    user: demoUser,
    jobDetails: {
      id: 'jd-3',
      listingId: 'mock-job-3',
      jobType: 'FULL_TIME',
      experienceLevel: 'Mid-Level',
      isRemote: false,
      salaryMin: 1200,
      salaryMax: 1800,
      salaryCurrency: 'EUR',
      salaryPeriod: 'MONTHLY',
      skills: ['Google Ads', 'Meta Ads', 'SEO', 'Analytics'],
      benefits: ['Performance bonus', 'Training budget'],
      requirements: ['3+ years in digital marketing'],
      responsibilities: ['Manage campaigns', 'Analyze performance'],
      openPositions: 1,
      companyName: 'AdriaMedia',
    },
  },
  {
    id: 'mock-job-4',
    title: 'Financial Analyst',
    slug: 'financial-analyst-tirana',
    description: 'A leading Albanian bank is looking for a Financial Analyst to support investment decisions and financial planning. CFA certification preferred.',
    type: 'JOB',
    status: 'ACTIVE',
    price: 2200,
    priceUnit: '/month',
    currency: 'EUR',
    city: 'Tirana',
    country: 'Albania',
    images: ['https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&auto=format&fit=crop'],
    tags: ['finance', 'banking', 'analysis'],
    views: 189,
    isFeatured: false,
    isPremium: true,
    isUrgent: false,
    createdAt: '2026-05-18T14:00:00Z',
    updatedAt: '2026-05-18T14:00:00Z',
    userId: 'demo',
    categoryId: 'cat-finance',
    category: { id: 'cat-finance', name: 'Finance', slug: 'finance', icon: '💰', listingType: 'JOB' },
    user: demoUser,
    jobDetails: {
      id: 'jd-4',
      listingId: 'mock-job-4',
      jobType: 'FULL_TIME',
      experienceLevel: 'Senior',
      isRemote: false,
      salaryMin: 2000,
      salaryMax: 2800,
      salaryCurrency: 'EUR',
      salaryPeriod: 'MONTHLY',
      skills: ['Excel', 'Financial modeling', 'SQL'],
      benefits: ['Medical insurance', 'Pension plan'],
      requirements: ['Finance degree', '4+ years experience'],
      responsibilities: ['Financial reporting', 'Budget planning'],
      openPositions: 1,
      companyName: 'Banka Kombëtare',
    },
  },
  {
    id: 'mock-job-5',
    title: 'Sales Representative',
    slug: 'sales-representative-albania',
    description: 'Fast-growing FMCG company seeks energetic Sales Representatives to expand our distribution network across Albania. Car and phone provided.',
    type: 'JOB',
    status: 'ACTIVE',
    price: 900,
    priceUnit: '/month',
    currency: 'EUR',
    city: 'Vlorë',
    country: 'Albania',
    images: ['https://images.unsplash.com/photo-1521791136064-7986c2920216?w=800&auto=format&fit=crop'],
    tags: ['sales', 'fmcg', 'b2b'],
    views: 94,
    isFeatured: false,
    isPremium: false,
    isUrgent: false,
    createdAt: '2026-05-22T08:00:00Z',
    updatedAt: '2026-05-22T08:00:00Z',
    userId: 'demo',
    categoryId: 'cat-sales',
    category: { id: 'cat-sales', name: 'Sales', slug: 'sales', icon: '📊', listingType: 'JOB' },
    user: demoUser,
    jobDetails: {
      id: 'jd-5',
      listingId: 'mock-job-5',
      jobType: 'FULL_TIME',
      experienceLevel: 'Junior',
      isRemote: false,
      salaryMin: 700,
      salaryMax: 1200,
      salaryCurrency: 'EUR',
      salaryPeriod: 'MONTHLY',
      skills: ['Communication', 'Negotiation', 'CRM'],
      benefits: ['Company car', 'Phone', 'Commission'],
      requirements: ['1+ year in sales', 'Driving license'],
      responsibilities: ['Client acquisition', 'Territory management'],
      openPositions: 3,
      companyName: 'AlbaFoods',
    },
  },
  {
    id: 'mock-job-6',
    title: 'Civil Engineer',
    slug: 'civil-engineer-tirana',
    description: 'Major construction company hiring Civil Engineers for large-scale residential and commercial projects in Tirana. Competitive package with project bonuses.',
    type: 'JOB',
    status: 'ACTIVE',
    price: 2000,
    priceUnit: '/month',
    currency: 'EUR',
    city: 'Tirana',
    country: 'Albania',
    images: ['https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=800&auto=format&fit=crop'],
    tags: ['engineering', 'construction', 'civil'],
    views: 127,
    isFeatured: false,
    isPremium: false,
    isUrgent: false,
    createdAt: '2026-05-17T12:00:00Z',
    updatedAt: '2026-05-17T12:00:00Z',
    userId: 'demo',
    categoryId: 'cat-engineering',
    category: { id: 'cat-engineering', name: 'Engineering', slug: 'engineering', icon: '⚙️', listingType: 'JOB' },
    user: demoUser,
    jobDetails: {
      id: 'jd-6',
      listingId: 'mock-job-6',
      jobType: 'FULL_TIME',
      experienceLevel: 'Mid-Level',
      isRemote: false,
      salaryMin: 1800,
      salaryMax: 2400,
      salaryCurrency: 'EUR',
      salaryPeriod: 'MONTHLY',
      skills: ['AutoCAD', 'Project management', 'Structural analysis'],
      benefits: ['Project bonuses', 'Training'],
      requirements: ['Engineering degree', '3+ years experience'],
      responsibilities: ['Site supervision', 'Technical drawings'],
      openPositions: 2,
      companyName: 'AlbaConstruct',
    },
  },
];

export const mockRealEstate: Listing[] = [
  {
    id: 'mock-re-1',
    title: 'Modern 2BR Apartment in Blloku',
    slug: 'modern-2br-apartment-blloku',
    description: 'Stunning fully furnished 2-bedroom apartment in the heart of Blloku. High-end appliances, private parking, fiber internet. Walking distance to best restaurants and cafes.',
    type: 'REAL_ESTATE',
    status: 'ACTIVE',
    price: 800,
    priceUnit: '/month',
    currency: 'EUR',
    city: 'Tirana',
    location: 'Blloku, Tirana',
    country: 'Albania',
    images: ['https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&auto=format&fit=crop'],
    tags: ['apartment', 'furnished', 'blloku'],
    views: 412,
    isFeatured: true,
    isPremium: true,
    isUrgent: false,
    createdAt: '2026-05-20T10:00:00Z',
    updatedAt: '2026-05-20T10:00:00Z',
    userId: 'demo',
    categoryId: 'cat-apartments',
    category: { id: 'cat-apartments', name: 'Apartments', slug: 'apartments', icon: '🏢', listingType: 'REAL_ESTATE' },
    user: demoUser,
    propertyDetails: {
      id: 'pd-1',
      listingId: 'mock-re-1',
      propertyType: 'APARTMENT',
      deal: 'RENT',
      bedrooms: 2,
      bathrooms: 1,
      area: 85,
      floor: 4,
      totalFloors: 8,
      yearBuilt: 2019,
      furnished: true,
      parking: true,
      balcony: true,
      elevator: true,
      pool: false,
      gym: false,
      securitySystem: true,
      petFriendly: false,
      amenities: ['Air conditioning', 'Central heating', 'Fiber internet'],
    },
  },
  {
    id: 'mock-re-2',
    title: 'Luxury Villa with Pool in Sarandë',
    slug: 'luxury-villa-pool-sarande',
    description: 'Magnificent 4-bedroom villa with private pool and sea view in Sarandë. Perfect for summer residence or investment. Newly built, premium finishes throughout.',
    type: 'REAL_ESTATE',
    status: 'ACTIVE',
    price: 450000,
    priceUnit: '',
    currency: 'EUR',
    city: 'Sarandë',
    location: 'Sarandë Seafront',
    country: 'Albania',
    images: ['https://images.unsplash.com/photo-1613977257363-707ba9348227?w=800&auto=format&fit=crop'],
    tags: ['villa', 'pool', 'sea-view', 'luxury'],
    views: 638,
    isFeatured: true,
    isPremium: true,
    isUrgent: false,
    createdAt: '2026-05-18T10:00:00Z',
    updatedAt: '2026-05-18T10:00:00Z',
    userId: 'demo',
    categoryId: 'cat-villas',
    category: { id: 'cat-villas', name: 'Villas', slug: 'villas', icon: '🏰', listingType: 'REAL_ESTATE' },
    user: demoUser,
    propertyDetails: {
      id: 'pd-2',
      listingId: 'mock-re-2',
      propertyType: 'VILLA',
      deal: 'SALE',
      bedrooms: 4,
      bathrooms: 3,
      area: 280,
      floor: 1,
      totalFloors: 2,
      yearBuilt: 2023,
      furnished: true,
      parking: true,
      balcony: true,
      elevator: false,
      pool: true,
      gym: false,
      securitySystem: true,
      petFriendly: true,
      amenities: ['Private pool', 'Sea view', 'Garden', 'Smart home'],
    },
  },
  {
    id: 'mock-re-3',
    title: 'Studio Apartment Near University',
    slug: 'studio-apartment-university-tirana',
    description: 'Cozy studio apartment ideal for students or young professionals. Located 5 minutes from University of Tirana. Bills included. Available immediately.',
    type: 'REAL_ESTATE',
    status: 'ACTIVE',
    price: 350,
    priceUnit: '/month',
    currency: 'EUR',
    city: 'Tirana',
    location: 'Sheshi Nënë Tereza, Tirana',
    country: 'Albania',
    images: ['https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&auto=format&fit=crop'],
    tags: ['studio', 'student', 'affordable'],
    views: 289,
    isFeatured: false,
    isPremium: false,
    isUrgent: true,
    createdAt: '2026-05-22T09:00:00Z',
    updatedAt: '2026-05-22T09:00:00Z',
    userId: 'demo',
    categoryId: 'cat-apartments',
    category: { id: 'cat-apartments', name: 'Apartments', slug: 'apartments', icon: '🏢', listingType: 'REAL_ESTATE' },
    user: demoUser,
    propertyDetails: {
      id: 'pd-3',
      listingId: 'mock-re-3',
      propertyType: 'APARTMENT',
      deal: 'RENT',
      bedrooms: 1,
      bathrooms: 1,
      area: 38,
      floor: 2,
      totalFloors: 5,
      yearBuilt: 2005,
      furnished: true,
      parking: false,
      balcony: false,
      elevator: false,
      pool: false,
      gym: false,
      securitySystem: false,
      petFriendly: false,
      amenities: ['Bills included', 'WiFi', 'Washing machine'],
    },
  },
  {
    id: 'mock-re-4',
    title: 'Commercial Office Space in Tirana Center',
    slug: 'commercial-office-tirana-center',
    description: 'Prime office space in the business district of Tirana. Open plan, recently refurbished, 8 workstations, meeting room, and reception area. Ideal for startups or small teams.',
    type: 'REAL_ESTATE',
    status: 'ACTIVE',
    price: 1200,
    priceUnit: '/month',
    currency: 'EUR',
    city: 'Tirana',
    location: 'Rruga e Kavajës, Tirana',
    country: 'Albania',
    images: ['https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&auto=format&fit=crop'],
    tags: ['office', 'commercial', 'business'],
    views: 174,
    isFeatured: false,
    isPremium: true,
    isUrgent: false,
    createdAt: '2026-05-19T11:00:00Z',
    updatedAt: '2026-05-19T11:00:00Z',
    userId: 'demo',
    categoryId: 'cat-offices',
    category: { id: 'cat-offices', name: 'Offices', slug: 'offices', icon: '🏗️', listingType: 'REAL_ESTATE' },
    user: demoUser,
    propertyDetails: {
      id: 'pd-4',
      listingId: 'mock-re-4',
      propertyType: 'OFFICE',
      deal: 'RENT',
      bedrooms: 0,
      bathrooms: 1,
      area: 120,
      floor: 3,
      totalFloors: 6,
      yearBuilt: 2015,
      furnished: true,
      parking: true,
      balcony: false,
      elevator: true,
      pool: false,
      gym: false,
      securitySystem: true,
      petFriendly: false,
      amenities: ['Reception', 'Meeting room', 'High-speed internet', 'AC'],
    },
  },
  {
    id: 'mock-re-5',
    title: '3-Bedroom House in Durrës',
    slug: '3-bedroom-house-durres',
    description: 'Spacious 3-bedroom family house in a quiet neighborhood in Durrës. Large garden, garage, and storage room. 10 minutes from the beach. Perfect for families.',
    type: 'REAL_ESTATE',
    status: 'ACTIVE',
    price: 120000,
    priceUnit: '',
    currency: 'EUR',
    city: 'Durrës',
    location: 'Durrës, Albania',
    country: 'Albania',
    images: ['https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800&auto=format&fit=crop'],
    tags: ['house', 'family', 'garden', 'durres'],
    views: 203,
    isFeatured: false,
    isPremium: false,
    isUrgent: false,
    createdAt: '2026-05-16T10:00:00Z',
    updatedAt: '2026-05-16T10:00:00Z',
    userId: 'demo',
    categoryId: 'cat-houses',
    category: { id: 'cat-houses', name: 'Houses', slug: 'houses', icon: '🏠', listingType: 'REAL_ESTATE' },
    user: demoUser,
    propertyDetails: {
      id: 'pd-5',
      listingId: 'mock-re-5',
      propertyType: 'HOUSE',
      deal: 'SALE',
      bedrooms: 3,
      bathrooms: 2,
      area: 160,
      floor: 1,
      totalFloors: 2,
      yearBuilt: 2010,
      furnished: false,
      parking: true,
      balcony: true,
      elevator: false,
      pool: false,
      gym: false,
      securitySystem: false,
      petFriendly: true,
      amenities: ['Garden', 'Garage', 'Storage room', 'Terrace'],
    },
  },
  {
    id: 'mock-re-6',
    title: 'Land Plot in Shkodër — Investment Opportunity',
    slug: 'land-plot-shkoder-investment',
    description: '1200m² land plot with building permit in a developing area of Shkodër. Excellent investment opportunity as the area is rapidly expanding with new infrastructure.',
    type: 'REAL_ESTATE',
    status: 'ACTIVE',
    price: 85000,
    priceUnit: '',
    currency: 'EUR',
    city: 'Shkodër',
    location: 'Shkodër, Albania',
    country: 'Albania',
    images: ['https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&auto=format&fit=crop'],
    tags: ['land', 'investment', 'shkoder'],
    views: 98,
    isFeatured: false,
    isPremium: false,
    isUrgent: false,
    createdAt: '2026-05-15T10:00:00Z',
    updatedAt: '2026-05-15T10:00:00Z',
    userId: 'demo',
    categoryId: 'cat-land',
    category: { id: 'cat-land', name: 'Land', slug: 'land', icon: '🌿', listingType: 'REAL_ESTATE' },
    user: demoUser,
    propertyDetails: {
      id: 'pd-6',
      listingId: 'mock-re-6',
      propertyType: 'LAND',
      deal: 'SALE',
      area: 1200,
      furnished: false,
      parking: false,
      balcony: false,
      elevator: false,
      pool: false,
      gym: false,
      securitySystem: false,
      petFriendly: false,
      amenities: ['Building permit', 'Road access', 'Utilities nearby'],
    },
  },
];
